In [1]:
import numpy as np

In [2]:
def REF(A):

    m, n = A.shape
    A = A.astype(float)

    print(f"Input matrix \nA = \n{A}\n\n")
    
    I = 0
    for j in range(n):
        print(f"-----CONSIDER COL {j}-----\n")
        for i in range(m):
            if i >= I and A[i,j] != 0:
                print(f"CONSIDER ROW {I}\nSWAP rows {i} and {I}:")
                A[[I,i]] = A[[i,I]]
                print(f"A = \n{A}")
                A[I,:] /= A[I,j]
                A[I+1:,:] -= A[I+1:,[j]] * A[I,:]
                print(f"PIVOT at ({I},{j}): \nA = \n{A}\n\nROW {I} DONE.")
                I += 1
                break
        print(f"COL {j} DONE.\n")
    
    print("-----ALL COLs DONE-----\n")
    print(f"REF(A) = \n{A}")
    
    return A

In [3]:
A = np.array([[2, 0, 0, 1], [2, 1, 0, -1], [0, 0, 0, 1.]])
A

array([[ 2.,  0.,  0.,  1.],
       [ 2.,  1.,  0., -1.],
       [ 0.,  0.,  0.,  1.]])

In [4]:
A_ref = REF(A)

Input matrix 
A = 
[[ 2.  0.  0.  1.]
 [ 2.  1.  0. -1.]
 [ 0.  0.  0.  1.]]


-----CONSIDER COL 0-----

CONSIDER ROW 0
SWAP rows 0 and 0:
A = 
[[ 2.  0.  0.  1.]
 [ 2.  1.  0. -1.]
 [ 0.  0.  0.  1.]]
PIVOT at (0,0): 
A = 
[[ 1.   0.   0.   0.5]
 [ 0.   1.   0.  -2. ]
 [ 0.   0.   0.   1. ]]

ROW 0 DONE.
COL 0 DONE.

-----CONSIDER COL 1-----

CONSIDER ROW 1
SWAP rows 1 and 1:
A = 
[[ 1.   0.   0.   0.5]
 [ 0.   1.   0.  -2. ]
 [ 0.   0.   0.   1. ]]
PIVOT at (1,1): 
A = 
[[ 1.   0.   0.   0.5]
 [ 0.   1.   0.  -2. ]
 [ 0.   0.   0.   1. ]]

ROW 1 DONE.
COL 1 DONE.

-----CONSIDER COL 2-----

COL 2 DONE.

-----CONSIDER COL 3-----

CONSIDER ROW 2
SWAP rows 2 and 2:
A = 
[[ 1.   0.   0.   0.5]
 [ 0.   1.   0.  -2. ]
 [ 0.   0.   0.   1. ]]
PIVOT at (2,3): 
A = 
[[ 1.   0.   0.   0.5]
 [ 0.   1.   0.  -2. ]
 [ 0.   0.   0.   1. ]]

ROW 2 DONE.
COL 3 DONE.

-----ALL COLs DONE-----

REF(A) = 
[[ 1.   0.   0.   0.5]
 [ 0.   1.   0.  -2. ]
 [ 0.   0.   0.   1. ]]


-----