In [1]:
import numpy as np

In [7]:
def RREF(A, showsteps='No'):

    m, n = A.shape
    A = A.astype(float)

    if showsteps=='Yes':
        print(f"Input matrix \nA = \n{A}\n\n")
    
    I = 0
    for j in range(n):
        if showsteps=='Yes':
            print(f"-----CONSIDER COL {j}-----\n")
        for i in range(m):
            if i >= I and A[i,j] != 0:
                if showsteps=='Yes':
                    print(f"CONSIDER ROW {I}\nSWAP rows {i} and {I}:")
                A[[I,i]] = A[[i,I]]
                if showsteps=='Yes':
                    print(f"A = \n{A}")
                A[I,:] /= A[I,j]
                A[I+1:,:] -= A[I+1:,[j]] * A[I,:]
                A[:I,:] -= A[:I,[j]] * A[I,:]   # This line is added from the code in 5.1.
                if showsteps=='Yes':
                    print(f"PIVOT at ({I},{j}): \nA = \n{A}\n\nROW {I} DONE.")
                I += 1
                break
        if showsteps=='Yes':
            print(f"COL {j} DONE.\n")
    
    if showsteps=='Yes':
        print("-----ALL COLs DONE-----\n")
        print(f"RREF(A) = \n{A}")
    
    return A

In [9]:
A = np.array([[1, 1, 1, 1],
              [2, 3, -1, -1],
              [0, 1, 1, 0],
              [2, -1, 1, -1],
              [1, 1, -1, -2]])
b = np.array([[4, 3, 2, 1, 0]]).T
Ab = np.hstack((A,b))
Ab_rref = RREF(Ab)
print(Ab_rref)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [-0. -0. -0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [12]:
A2 = A.copy()
A2[-1,-1] = -1
A2b = np.hstack((A2,b))
A2b_rref = RREF(A2b)
print(A2b_rref)

[[ 1.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  1.]
 [ 0.  0.  1.  0.  1.]
 [-0. -0. -0.  1.  1.]
 [ 0.  0.  0.  0.  0.]]


In [13]:
# Exercise 2.17
A = np.array([[1, 1, -1, -1], 
              [1, -1, 1, 1],
              [0, 1, -2, 0],
              [1, 1, 3, 2]])
b = np.array([[0, 2, -1, 7]]).T
Ab = np.hstack((A,b))
Ab_rref = RREF(Ab)
print(Ab_rref)

[[1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 1.]]


In [15]:
# Exercise 2.18
Ab = np.array([[2, 1, -3, 1],
               [1, -1, 1, 1],
               [3, 0, -2, 2]])
Ab_rref = RREF(Ab)
print(Ab_rref)

[[ 1.          0.         -0.66666667  0.66666667]
 [-0.          1.         -1.66666667 -0.33333333]
 [ 0.          0.          0.          0.        ]]


In [16]:
# Exercise 2.19
Ab = np.array([[1, 2, -1, 1, 0, 3],
               [2, -2, -2, 0, -1, 2],
               [2, 0, -3, 0, 0, -1]])
Ab_rref = RREF(Ab)
print(Ab_rref)

[[ 1.          0.          0.          1.         -1.          6.        ]
 [-0.          1.          0.          0.33333333  0.16666667  0.66666667]
 [-0.         -0.          1.          0.66666667 -0.66666667  4.33333333]]
