# Gram-Schmidt orthogonalization

Recall when $\mathcal{U} = \{v_{1},v_{2},\dots,v_{n}\}$ is a basis of a vector space $V$, then we can construct an *orthogonal basis* out of $\mathcal{U}$ using the following Gram-Schmidt process:
$$
\begin{align*}
v_{1}' &= v_{1} \\
v_{2}' &= v_{2} - proj_{v_{1}'} (v_{2}) \\
v_{3}' &= v_{3} - proj_{v_{1}'} (v_{3}) - proj_{v_{2}'} (v_{3}) \\
& \vdots \\
v_{i}' &= v_{i} - proj_{v_{1}'} (v_{i}) - \dots - proj_{v_{i-1}'} (v_{i}) \\
& \vdots \\
v_{n}' &= v_{n} - proj_{v_{1}'} (v_{n}) - \dots - proj_{v_{n-1}'} (v_{n}).
\end{align*}
$$

In [1]:
import numpy as np

In [2]:
def proj(x,y):
    p = (x.T@y)/(y.T@y) * y
    return p

def orthog(U):
    """
    The input U is a matrix of shape (m,n), whose columns constitute a basis of a vector space.
    """
    n = np.shape(U)[1]
    Vp = np.zeros(np.shape(U))
    for i in range(n):
        u_i = U[:,i].copy()
        Vp[:,i] = U[:,i]
        for j in range(i):
            p_j = proj(u_i,Vp[:,j])
            Vp[:,i] -= p_j
    return Vp

In [3]:
U = np.array([[1, 1], [2, 0]])
Up = orthog(U)
print(f"The orthogonal basis constructed using the Gram-Schmidt process is\nU' = \n{Up}.")

The orthogonal basis constructed using the Gram-Schmidt process is
U' = 
[[ 1.   0.8]
 [ 2.  -0.4]].


In [4]:
# double check that U' is orthogonal by testing if U'@U is diagonal.
Up.T@Up

array([[5. , 0. ],
       [0. , 0.8]])

In [5]:
U = np.array([[1, 1, 0, 0], [0, 1, 1, 0], [1, 0, 0, 0], [0, 0, 1, 1]])
np.linalg.matrix_rank(U)

np.int64(4)

In [6]:
Up = orthog(U)
print(f"The orthogonal basis constructed using the Gram-Schmidt process is\nU' = \n{Up}.")

The orthogonal basis constructed using the Gram-Schmidt process is
U' = 
[[ 1.          0.5        -0.33333333  0.25      ]
 [ 0.          1.          0.33333333 -0.25      ]
 [ 1.         -0.5         0.33333333 -0.25      ]
 [ 0.          0.          1.          0.25      ]].


In [7]:
Up.T@Up

array([[ 2.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  1.50000000e+00,  5.55111512e-17,
        -5.55111512e-17],
       [ 0.00000000e+00,  5.55111512e-17,  1.33333333e+00,
         1.38777878e-16],
       [ 0.00000000e+00, -5.55111512e-17,  1.38777878e-16,
         2.50000000e-01]])