# MTH202 Worksheet 9

In [1]:
import numpy as np

In [2]:
def proj(x,y):
    p = (x.T@y)/(y.T@y) * y
    return p

def orthog(U):
    """
    The input U is a matrix of shape (m,n), whose columns constitute a basis of a vector space.
    """
    n = np.shape(U)[1]
    Vp = np.zeros(np.shape(U))
    for i in range(n):
        u_i = U[:,i].copy()
        Vp[:,i] = U[:,i]
        for j in range(i):
            p_j = proj(u_i,Vp[:,j])
            Vp[:,i] -= p_j
    return Vp

## Problem 1

### Problem 1.1

Write a `python` function that *orthonormalize* a given basis.

In [3]:
def orthonormalize(U):
    U_orthog = orthog(U)
    col_norms = np.linalg.norm(U_orthog, axis=0).reshape((1,-1))
    U_orthonormalized = U_orthog/col_norms
    return U_orthonormalized

### Problem 1.2
Test your function with the following basis given in a matrix `U`.

In [4]:
U = np.array([[1, 2, 3, 1],
              [0, 1, 0, 1],
              [1, 0, 0, 1],
              [-1, 0, 1, 0]])

In [5]:
U_orthonormalized = orthonormalize(U)
print(U_orthonormalized)

[[ 0.57735027  0.69631062  0.38533732 -0.18257419]
 [ 0.          0.52223297 -0.77067464  0.36514837]
 [ 0.57735027 -0.34815531  0.11009638  0.73029674]
 [-0.57735027  0.34815531  0.49543369  0.54772256]]


In [6]:
np.isclose(U_orthonormalized.T @ U_orthonormalized, np.eye(4,4))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Problem 2

Consider a vector space $V = \{ (x_{1},x_{2},x_{3} \in \mathbb{R}^{3} \mid x_{1} - x_{2} + x_{3} = 0 \}$.
* Find a basis of $V$.
* Use the function from Problem 1 to orthonormalize such basis.

In [7]:
B = np.array([[1, 1, 0], [-1, 0, 1]]).T
B_orthonormalized = orthonormalize(B)
print(B_orthonormalized)

[[ 0.70710678 -0.40824829]
 [ 0.70710678  0.40824829]
 [ 0.          0.81649658]]


-----