# MTH202 Worksheet 7

In [1]:
import numpy as np

## Problem 1

Find the following of the matrix $A$ given below.
- $\mathrm{rank}(A)$,
- $\mathrm{det}(A)$,
- $(A^{\top})^{-1}$.

In [11]:
np.random.seed(42)

A = np.random.randint(-5, 6, (5,5))
A

array([[ 1, -2,  5,  2, -1],
       [ 1,  4, -3,  1,  5],
       [ 5,  2, -1, -2,  2],
       [ 2, -3,  0, -1, -4],
       [ 2,  0, -4, -1, -5]])

In [12]:
print(f"rank(A) = {np.linalg.matrix_rank(A)}")
print(f"det(A) = {np.linalg.det(A)}")
print(f"inv(A.T) =\n{np.linalg.inv(A.T)}")

rank(A) = 5
det(A) = 960.0000000000001
inv(A.T) =
[[ 0.10625     0.12083333  0.11458333  0.23333333 -0.09583333]
 [ 0.128125   -0.25625    -0.234375    0.35        0.16875   ]
 [ 0.084375    0.16458333  0.13020833 -0.21666667 -0.02708333]
 [ 0.15625    -0.64583333 -0.30208333  0.16666667  0.27083333]
 [ 0.015625    0.30208333  0.03645833  0.08333333 -0.23958333]]


## Problem 2

Diagonalize the matrix $B = A^{\top}A$, where $A$ is defined in Problem 1.
That is, find $V$ and $\Lambda$ in which
$$
B = V \Lambda V^{-1}.
$$

In [17]:
B = A.T @ A
eigvals, eigvecs = np.linalg.eig(B)
Lambda = np.diag(eigvals)
V = eigvecs
print(f"Lambda =\n{Lambda}")
print(f"V =\n{V}")

Lambda =
[[99.37288987  0.          0.          0.          0.        ]
 [ 0.         66.50052903  0.          0.          0.        ]
 [ 0.          0.         29.31667481  0.          0.        ]
 [ 0.          0.          0.          4.82373803  0.        ]
 [ 0.          0.          0.          0.          0.98616826]]
V =
[[ 0.05755564  0.4385994   0.85922725 -0.21006746  0.14804766]
 [ 0.5578303   0.12508422 -0.04059854 -0.29174776 -0.76577692]
 [-0.31908993 -0.71718995  0.47096218  0.06111978 -0.39784316]
 [ 0.00874114 -0.31775504 -0.10839702 -0.89275129  0.30033405]
 [ 0.76394889 -0.42030323  0.16286498  0.26460236  0.37840173]]


In [20]:
# Double check that B and V Lambda V^-1 are the same.
B_recon = V @ Lambda @ np.linalg.inv(V)
np.isclose(B, B_recon)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Problem 3

Use `np.linalg.eig` to compute the SVD of a matrix
$$
B = 
\begin{bmatrix}
0 & 0 & 1 & 1 \\
1 & 1 & 0 & 0
\end{bmatrix}.
$$